<a href="https://colab.research.google.com/github/umarsaleh702-stack/pytorch-Exercises/blob/main/Umar00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [ ]:
# Import torch
import torch


# Create random tensor
random_tensor=torch.tensor([7,7])
random_tensor


tensor([7, 7])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [ ]:
# Create another random tensor
random_tensor1=torch.tensor([1,7])


# Perform matrix multiplication
multiplied_matrix=torch.matmul(random_tensor, random_tensor1)
multiplied_matrix


tensor(56)

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [ ]:
# Set manual seed
torch.manual_seed(42)

# Create two random tensors
tensor1=torch.rand([9,7])
tensor2=torch.rand([7,5])
multiplication=torch.matmul(tensor1, tensor2)
multiplication


# Matrix multiply tensors


tensor([[1.6394, 2.3817, 2.0645, 2.4088, 2.6886],
        [1.9653, 2.6865, 2.3334, 2.8578, 2.8415],
        [1.2579, 1.7603, 1.4808, 1.9019, 2.2532],
        [0.6854, 0.9260, 0.9392, 1.2910, 1.4285],
        [1.0068, 1.5702, 1.1140, 1.9094, 1.5196],
        [1.4026, 1.8955, 1.7013, 2.2159, 2.4564],
        [1.6980, 2.0377, 2.1674, 3.0162, 2.6510],
        [1.1955, 1.4852, 1.0456, 1.8834, 1.1991],
        [1.2381, 1.2856, 1.3104, 2.2019, 1.7556]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
# Set random seed on the GPU
seed=1234

torch.cuda.manual_seed(seed)



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [ ]:
# Set random seed

torch.manual_seed(1234)

# Check for access to GPU
device="cuda" if torch.cuda. is_available() else "cpu"
device

# Create two random tensors on GPU
first_tensor=torch.rand([2,3])
second_tensor=torch.rand([2,3])
print(first_tensor, device)
print(second_tensor, device)


tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]]) cuda
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]]) cuda



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [ ]:
# Perform matmul on tensor_A and tensor_B
operation_multiplication=torch.matmul(first_tensor, second_tensor.reshape(3,2))
operation_multiplication, operation_multiplication.shape, device


(tensor([[0.4759, 0.2931],
         [0.6074, 0.5855]]),
 torch.Size([2, 2]),
 'cuda')

### 8. Find the maximum and minimum values of the output of 7.

In [ ]:
# Find max
max=torch.max(operation_multiplication)
indices=torch.argmax(operation_multiplication)
print(max, indices )



# Find min
min=torch.min(operation_multiplication)
indices=torch.argmin(operation_multiplication)
print(min, indices)


tensor(0.6074) tensor(2)
tensor(0.2931) tensor(1)


### 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
# Find arg max
indices1=torch.argmax(operation_multiplication)
print(indices1)


# Find arg min
indices2=torch.argmin(operation_multiplication)
print(indices2)


tensor(2)
tensor(1)



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
# Set seed
torch.manual_seed(7)


# Create random tensor
tensor=torch.rand(1,1,1,10)
print(tensor, tensor.shape)
# Remove single dimensions
squeezed_tensor=torch.squeeze(tensor)


# Print out tensors and their shapes
print(squeezed_tensor, squeezed_tensor.shape)


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
